import random

def generate_private_number(p):
    pri_key = random.randint(1, p - 1)
    # print("random:", pri_key)
    return pri_key


def generate_public_key(pub_key, p, g):
    print("\t\t\t", g, '^', pub_key, "mod", p, "=", pow(g, pub_key, p))
    pub_key = pow(g, pub_key, p)
    return pub_key


def generate_shared_secret(private_key, public_key, p):
    print("\t\t\t", public_key, '^', private_key, "mod",
          p, "=", pow(public_key, private_key, p))
    shrd_key = pow(public_key, private_key, p)
    return shrd_key


def encrypt_message(message, shared_secret):
    # XOR the message with the shared secret to encrypt the message
    encrypted_message = ''.join(chr(ord(c) ^ shared_secret) for c in message)
    return encrypted_message


def decrypt_message(encrypted_message, shared_secret):
    # XOR the encrypted message with the shared secret to decrypt the message
    message = ''.join(chr(ord(c) ^ shared_secret) for c in encrypted_message)
    return message

# Example usage:


# Select two large prime numbers, p and g
# p = 17
# g = 3
p = 100043
g = 100003

print("Bob and alice agreement:", g, "mod", p)

# Generate private keys
alice_private_num = generate_private_number(p)
print("alice_private_num:\t", alice_private_num)
bob_private_num = generate_private_number(p)
print("bob_private_num:\t", bob_private_num)


# Generate public keys
print("alice_public_key:")
alice_public_key = generate_public_key(alice_private_num, p, g)
print("bob_public_key:")
bob_public_key = generate_public_key(bob_private_num, p, g)

# Exchange public keys

# Generate shared secret
print("alice_shared_secret:")
alice_shared_secret = generate_shared_secret(
    alice_private_num, bob_public_key, p)
print("bob_shared_secret:")
bob_shared_secret = generate_shared_secret(
    bob_private_num, alice_public_key, p)

# The shared secrets generated by both parties should be the same
assert alice_shared_secret == bob_shared_secret

# Alice encrypts a message
message = "Hello Bob, how are you?"
encrypted_message = encrypt_message(message, alice_shared_secret)
print("\nencrypted_message:", encrypted_message)
# Bob decrypts the message
# you can try alice_shared_secret key to decrypt the message
decrypted_message = decrypt_message(encrypted_message, bob_shared_secret)
print("bob decryption using his shared_secret_key:", decrypted_message)
decrypted_message = decrypt_message(encrypted_message, alice_shared_secret)
print("bob decryption using alice's shared_secret_key:", decrypted_message)

# trying to decrypt the message using a number. output with error
print("\nEve trying to decrypt the message using a random key")
decrypted_message = decrypt_message(encrypted_message, 2334)
print("decrypted_message:", decrypted_message)  #

# The decrypted message should be the same as the original message
assert message == decrypted_message, "Decryption error"
